#spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username=postgres
spring.datasource.password=1234
